// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "inventory/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an exported alias for the unexported repository struct
type MockRepository struct {
	repository
}

func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	return &MockRepository{repository: *newRepository(t)}
}

// repository is an autogenerated mock type for the Repository type
type repository struct {
	mock.Mock
}

type repository_Expecter struct {
	mock *mock.Mock
}

func (_m *repository) EXPECT() *repository_Expecter {
	return &repository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx
func (_m *repository) FindAll(ctx context.Context) ([]*model.Part, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Part, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Part); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// repository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type repository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *repository_Expecter) FindAll(ctx interface{}) *repository_FindAll_Call {
	return &repository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *repository_FindAll_Call) Run(run func(ctx context.Context)) *repository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *repository_FindAll_Call) Return(_a0 []*model.Part, _a1 error) *repository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *repository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*model.Part, error)) *repository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUUID provides a mock function with given fields: ctx, uuid
func (_m *repository) FindByUUID(ctx context.Context, uuid string) (*model.Part, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for FindByUUID")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// repository_FindByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUUID'
type repository_FindByUUID_Call struct {
	*mock.Call
}

// FindByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *repository_Expecter) FindByUUID(ctx interface{}, uuid interface{}) *repository_FindByUUID_Call {
	return &repository_FindByUUID_Call{Call: _e.mock.On("FindByUUID", ctx, uuid)}
}

func (_c *repository_FindByUUID_Call) Run(run func(ctx context.Context, uuid string)) *repository_FindByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *repository_FindByUUID_Call) Return(_a0 *model.Part, _a1 error) *repository_FindByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *repository_FindByUUID_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *repository_FindByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *repository) Save(ctx context.Context, _a1 *model.Part) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Part) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.Part
func (_e *repository_Expecter) Save(ctx interface{}, _a1 interface{}) *repository_Save_Call {
	return &repository_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *repository_Save_Call) Run(run func(ctx context.Context, _a1 *model.Part)) *repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Part))
	})
	return _c
}

func (_c *repository_Save_Call) Return(_a0 error) *repository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *repository_Save_Call) RunAndReturn(run func(context.Context, *model.Part) error) *repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newRepository creates a new instance of repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *repository {
	mock := &repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

