package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentClient is an autogenerated mock type for the PaymentClient type
type MockPaymentClient struct {
	mock.Mock
}

// PayOrder provides a mock function
func (_m *MockPaymentClient) PayOrder(ctx context.Context, userUUID string, orderUUID string, paymentMethod string) (string, error) {
	ret := _m.Called(ctx, userUUID, orderUUID, paymentMethod)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, userUUID, orderUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userUUID, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
