package mocks

import (
	context "context"
	model "github.com/irina-lat/microservices-course/order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockInventoryClient is an autogenerated mock type for the InventoryClient type
type MockInventoryClient struct {
	mock.Mock
}

// ListParts provides a mock function
func (_m *MockInventoryClient) ListParts(ctx context.Context, partUUIDs []string) ([]*model.Part, error) {
	ret := _m.Called(ctx, partUUIDs)

	var r0 []*model.Part
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Part); ok {
		r0 = rf(ctx, partUUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
