version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - revive

formatters:
  enable:
    - gofmt
  

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - bin
    - internal/repository/mocks
    - internal/service/mocks
    - shared/pkg/openapi
    - shared/pkg/proto