// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// service is an autogenerated mock type for the Service type
type service struct {
	mock.Mock
}

type service_Expecter struct {
	mock *mock.Mock
}

func (_m *service) EXPECT() *service_Expecter {
	return &service_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, userUUID, paymentMethod
func (_m *service) PayOrder(ctx context.Context, orderUUID string, userUUID string, paymentMethod string) (string, error) {
	ret := _m.Called(ctx, orderUUID, userUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, orderUUID, userUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, orderUUID, userUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, orderUUID, userUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// service_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type service_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - userUUID string
//   - paymentMethod string
func (_e *service_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, userUUID interface{}, paymentMethod interface{}) *service_PayOrder_Call {
	return &service_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, userUUID, paymentMethod)}
}

func (_c *service_PayOrder_Call) Run(run func(ctx context.Context, orderUUID string, userUUID string, paymentMethod string)) *service_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *service_PayOrder_Call) Return(_a0 string, _a1 error) *service_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *service_PayOrder_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *service_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// newService creates a new instance of service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newService(t interface {
	mock.TestingT
	Cleanup(func())
}) *service {
	mock := &service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
