// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "inventory/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// service is an autogenerated mock type for the Service type
type service struct {
	mock.Mock
}

type service_Expecter struct {
	mock *mock.Mock
}

func (_m *service) EXPECT() *service_Expecter {
	return &service_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, uuid
func (_m *service) GetPart(ctx context.Context, uuid string) (*model.Part, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// service_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type service_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *service_Expecter) GetPart(ctx interface{}, uuid interface{}) *service_GetPart_Call {
	return &service_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uuid)}
}

func (_c *service_GetPart_Call) Run(run func(ctx context.Context, uuid string)) *service_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *service_GetPart_Call) Return(_a0 *model.Part, _a1 error) *service_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *service_GetPart_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *service_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *service) ListParts(ctx context.Context, filter *model.PartsFilter) ([]*model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) ([]*model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) []*model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// service_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type service_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.PartsFilter
func (_e *service_Expecter) ListParts(ctx interface{}, filter interface{}) *service_ListParts_Call {
	return &service_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *service_ListParts_Call) Run(run func(ctx context.Context, filter *model.PartsFilter)) *service_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PartsFilter))
	})
	return _c
}

func (_c *service_ListParts_Call) Return(_a0 []*model.Part, _a1 error) *service_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *service_ListParts_Call) RunAndReturn(run func(context.Context, *model.PartsFilter) ([]*model.Part, error)) *service_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// newService creates a new instance of service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newService(t interface {
	mock.TestingT
	Cleanup(func())
}) *service {
	mock := &service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

