// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// repository is an autogenerated mock type for the Repository type
type repository struct {
	mock.Mock
}

type repository_Expecter struct {
	mock *mock.Mock
}

func (_m *repository) EXPECT() *repository_Expecter {
	return &repository_Expecter{mock: &_m.Mock}
}

// FindByUUID provides a mock function with given fields: ctx, uuid
func (_m *repository) FindByUUID(ctx context.Context, uuid string) (*model.Order, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for FindByUUID")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// repository_FindByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUUID'
type repository_FindByUUID_Call struct {
	*mock.Call
}

// FindByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *repository_Expecter) FindByUUID(ctx interface{}, uuid interface{}) *repository_FindByUUID_Call {
	return &repository_FindByUUID_Call{Call: _e.mock.On("FindByUUID", ctx, uuid)}
}

func (_c *repository_FindByUUID_Call) Run(run func(ctx context.Context, uuid string)) *repository_FindByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *repository_FindByUUID_Call) Return(_a0 *model.Order, _a1 error) *repository_FindByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *repository_FindByUUID_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *repository_FindByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *repository) Save(ctx context.Context, _a1 *model.Order) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.Order
func (_e *repository_Expecter) Save(ctx interface{}, _a1 interface{}) *repository_Save_Call {
	return &repository_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *repository_Save_Call) Run(run func(ctx context.Context, _a1 *model.Order)) *repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *repository_Save_Call) Return(_a0 error) *repository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *repository_Save_Call) RunAndReturn(run func(context.Context, *model.Order) error) *repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *repository) Update(ctx context.Context, _a1 *model.Order) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.Order
func (_e *repository_Expecter) Update(ctx interface{}, _a1 interface{}) *repository_Update_Call {
	return &repository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *repository_Update_Call) Run(run func(ctx context.Context, _a1 *model.Order)) *repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *repository_Update_Call) Return(_a0 error) *repository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *repository_Update_Call) RunAndReturn(run func(context.Context, *model.Order) error) *repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newRepository creates a new instance of repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *repository {
	mock := &repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
