// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// payment_client is an autogenerated mock type for the PaymentClient type
type payment_client struct {
	mock.Mock
}

type payment_client_Expecter struct {
	mock *mock.Mock
}

func (_m *payment_client) EXPECT() *payment_client_Expecter {
	return &payment_client_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, userUUID, orderUUID, paymentMethod
func (_m *payment_client) PayOrder(ctx context.Context, userUUID string, orderUUID string, paymentMethod string) (string, error) {
	ret := _m.Called(ctx, userUUID, orderUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, userUUID, orderUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, userUUID, orderUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userUUID, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// payment_client_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type payment_client_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - orderUUID string
//   - paymentMethod string
func (_e *payment_client_Expecter) PayOrder(ctx interface{}, userUUID interface{}, orderUUID interface{}, paymentMethod interface{}) *payment_client_PayOrder_Call {
	return &payment_client_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, userUUID, orderUUID, paymentMethod)}
}

func (_c *payment_client_PayOrder_Call) Run(run func(ctx context.Context, userUUID string, orderUUID string, paymentMethod string)) *payment_client_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *payment_client_PayOrder_Call) Return(_a0 string, _a1 error) *payment_client_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *payment_client_PayOrder_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *payment_client_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// newPayment_client creates a new instance of payment_client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newPayment_client(t interface {
	mock.TestingT
	Cleanup(func())
}) *payment_client {
	mock := &payment_client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
