// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// inventory_client is an autogenerated mock type for the InventoryClient type
type inventory_client struct {
	mock.Mock
}

type inventory_client_Expecter struct {
	mock *mock.Mock
}

func (_m *inventory_client) EXPECT() *inventory_client_Expecter {
	return &inventory_client_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function with given fields: ctx, partUUIDs
func (_m *inventory_client) ListParts(ctx context.Context, partUUIDs []string) ([]*model.Part, error) {
	ret := _m.Called(ctx, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Part, error)); ok {
		return rf(ctx, partUUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Part); ok {
		r0 = rf(ctx, partUUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// inventory_client_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type inventory_client_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUIDs []string
func (_e *inventory_client_Expecter) ListParts(ctx interface{}, partUUIDs interface{}) *inventory_client_ListParts_Call {
	return &inventory_client_ListParts_Call{Call: _e.mock.On("ListParts", ctx, partUUIDs)}
}

func (_c *inventory_client_ListParts_Call) Run(run func(ctx context.Context, partUUIDs []string)) *inventory_client_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *inventory_client_ListParts_Call) Return(_a0 []*model.Part, _a1 error) *inventory_client_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *inventory_client_ListParts_Call) RunAndReturn(run func(context.Context, []string) ([]*model.Part, error)) *inventory_client_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// newInventory_client creates a new instance of inventory_client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newInventory_client(t interface {
	mock.TestingT
	Cleanup(func())
}) *inventory_client {
	mock := &inventory_client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
