// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// service is an autogenerated mock type for the Service type
type service struct {
	mock.Mock
}

type service_Expecter struct {
	mock *mock.Mock
}

func (_m *service) EXPECT() *service_Expecter {
	return &service_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, orderUUID
func (_m *service) CancelOrder(ctx context.Context, orderUUID string) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// service_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type service_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *service_Expecter) CancelOrder(ctx interface{}, orderUUID interface{}) *service_CancelOrder_Call {
	return &service_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderUUID)}
}

func (_c *service_CancelOrder_Call) Run(run func(ctx context.Context, orderUUID string)) *service_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *service_CancelOrder_Call) Return(_a0 error) *service_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *service_CancelOrder_Call) RunAndReturn(run func(context.Context, string) error) *service_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, userUUID, partUUIDs
func (_m *service) CreateOrder(ctx context.Context, userUUID string, partUUIDs []string) (*model.Order, error) {
	ret := _m.Called(ctx, userUUID, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (*model.Order, error)); ok {
		return rf(ctx, userUUID, partUUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) *model.Order); ok {
		r0 = rf(ctx, userUUID, partUUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, userUUID, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// service_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type service_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - partUUIDs []string
func (_e *service_Expecter) CreateOrder(ctx interface{}, userUUID interface{}, partUUIDs interface{}) *service_CreateOrder_Call {
	return &service_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userUUID, partUUIDs)}
}

func (_c *service_CreateOrder_Call) Run(run func(ctx context.Context, userUUID string, partUUIDs []string)) *service_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *service_CreateOrder_Call) Return(_a0 *model.Order, _a1 error) *service_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *service_CreateOrder_Call) RunAndReturn(run func(context.Context, string, []string) (*model.Order, error)) *service_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, orderUUID
func (_m *service) GetOrder(ctx context.Context, orderUUID string) (*model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// service_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type service_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *service_Expecter) GetOrder(ctx interface{}, orderUUID interface{}) *service_GetOrder_Call {
	return &service_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderUUID)}
}

func (_c *service_GetOrder_Call) Run(run func(ctx context.Context, orderUUID string)) *service_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *service_GetOrder_Call) Return(_a0 *model.Order, _a1 error) *service_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *service_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *service_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, paymentMethod
func (_m *service) PayOrder(ctx context.Context, orderUUID string, paymentMethod string) (string, error) {
	ret := _m.Called(ctx, orderUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, orderUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, orderUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// service_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type service_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - paymentMethod string
func (_e *service_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, paymentMethod interface{}) *service_PayOrder_Call {
	return &service_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, paymentMethod)}
}

func (_c *service_PayOrder_Call) Run(run func(ctx context.Context, orderUUID string, paymentMethod string)) *service_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *service_PayOrder_Call) Return(_a0 string, _a1 error) *service_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *service_PayOrder_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *service_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function with given fields: ctx, orderUUID, status
func (_m *service) UpdateOrderStatus(ctx context.Context, orderUUID string, status model.OrderStatus) error {
	ret := _m.Called(ctx, orderUUID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderStatus) error); ok {
		r0 = rf(ctx, orderUUID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// service_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type service_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - status model.OrderStatus
func (_e *service_Expecter) UpdateOrderStatus(ctx interface{}, orderUUID interface{}, status interface{}) *service_UpdateOrderStatus_Call {
	return &service_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, orderUUID, status)}
}

func (_c *service_UpdateOrderStatus_Call) Run(run func(ctx context.Context, orderUUID string, status model.OrderStatus)) *service_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.OrderStatus))
	})
	return _c
}

func (_c *service_UpdateOrderStatus_Call) Return(_a0 error) *service_UpdateOrderStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *service_UpdateOrderStatus_Call) RunAndReturn(run func(context.Context, string, model.OrderStatus) error) *service_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// newService creates a new instance of service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newService(t interface {
	mock.TestingT
	Cleanup(func())
}) *service {
	mock := &service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
